/**
 * Writes one readable review sheet per content pack to docs/content-review/ (run: npm run content:review).
 * A person reads it top to bottom, checks every fact, answer and explanation, and signs each question.
 * Re-run it after every content change; it never edits the content itself.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { PACKS } from '../src/content';
import { materializeQuestion } from '../src/core/engine';
import { createDefaultGenerators } from '../src/generators';
import type { ContentPack, Question } from '../src/core/types';

const gens = createDefaultGenerators();
const md = (s: string) => s.replace(/\|/g, '\\|');

function questionBlock(q: Question, title: string, note = ''): string {
  const lines = [`#### ${title}${note}`, `Concept: **${q.concept}** | Difficulty: ${q.difficulty}`, '', `**${md(q.prompt)}**`];
  if (q.code) lines.push('', '```', q.code, '```');
  lines.push('', '| | Answer | Mistake it shows |', '|---|---|---|');
  for (const o of q.options) lines.push(`| ${o.correct ? 'CORRECT' : ''} | ${md(o.text)} | ${o.correct ? '' : o.misconception} |`);
  lines.push('', 'Feedback shown for each wrong answer:');
  for (const o of q.options.filter((x) => !x.correct)) lines.push(`- **${o.misconception}**: ${q.feedback?.[o.misconception!]?.plain ?? '(missing)'}${q.feedback?.[o.misconception!]?.counter ? ` Counterexample: ${q.feedback[o.misconception!]!.counter}` : ''}`);
  lines.push('', `Hints: ${q.hints.map((h, i) => `(${i + 1}) ${h}`).join(' ')}`);
  return lines.join('\n');
}

function sheet(pack: ContentPack): string {
  const out: string[] = [
    `# Review sheet: ${pack.title} (pack ${pack.id}, version ${pack.version})`,
    '',
    '<!-- generated by npm run content:review; do not edit by hand -->',
    'Read everything below. For every item check: the **fact is true**, the **marked answer is the only correct one**, each wrong answer shows the **mistake named**, and the **words are clear for a student**. Then fill in the sign-off line. Facts in code are also run in real Python by `npm run verify:content`; science and other facts can only be checked by a person.',
    '',
    `Sign-off: Reviewed by ______  Date ______  All items OK: yes / no`,
    '',
    '## Topics',
  ];
  for (const c of pack.concepts) {
    out.push('', `### ${c.title} (\`${c.id}\`)`, `Needs first: ${c.prerequisites.join(', ') || 'nothing'}`, `Summary: ${c.summary}`, `Words a student might use: ${c.keywords.join(', ')}`);
    for (const [style, text] of Object.entries(c.explanations)) out.push('', `**Explanation (${style}):** ${text}`);
    out.push('', 'A good "teach me back" answer covers:', ...c.teachBack.map((t) => `- ${t.label} (counts if it contains one of: ${t.keywords.join(', ')})`));
    out.push('', 'Review: [ ] facts true   [ ] clear words   Notes: ______');
  }
  out.push('', '## Mistakes (misconceptions) this pack can find', '', '| Id | Topic | Name shown | What the student wrongly believes | Short correction |', '|---|---|---|---|---|');
  for (const m of pack.misconceptions) out.push(`| ${m.id} | ${m.concept} | ${md(m.title)} | ${md(m.description)} | ${md(m.explanations.plain ?? '')} |`);
  out.push('', '## Questions');
  for (const spec of pack.questions) {
    if (spec.kind === 'static') {
      out.push('', questionBlock(materializeQuestion(spec, gens, 1), `${spec.id} (written by hand)`), '', 'Review: [ ] fact true  [ ] one correct answer  [ ] mistakes match  [ ] clear   Reviewed by ______  Notes: ______');
    } else {
      out.push('', `### ${spec.id} (made by the generator \`${spec.generator}\`; three examples below)`);
      for (const seed of [1, 2, 3]) out.push('', questionBlock(materializeQuestion(spec, gens, seed), `${spec.id}, example ${seed}`));
      out.push('', 'Review: [ ] examples correct  [ ] mistakes match  [ ] clear   Reviewed by ______  Notes: ______');
    }
  }
  return out.join('\n') + '\n';
}

mkdirSync('docs/content-review', { recursive: true });
for (const p of PACKS) {
  writeFileSync(`docs/content-review/${p.id}.md`, sheet(p));
  console.log(`wrote docs/content-review/${p.id}.md (${p.concepts.length} topics, ${p.misconceptions.length} mistakes, ${p.questions.length} questions)`);
}
