/**
 * Generates the numbers for docs/EVIDENCE.md (task D4). Run: npm run evidence
 * Part 1: simulated learners, NOVA vs a memoryless baseline (the real engine runs inside).
 * Part 2: how long the engine takes (measured in Node on THIS computer; use the in-app device check for a weak device).
 * It writes docs/evidence-data/simulation.md and simulation.json.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { cpus } from 'node:os';
import { PACKS } from '../src/content';
import { applyAttempt, createLearner, materializeQuestion, nextDiagnosticQuestion, planToday, selectQuestion } from '../src/core/engine';
import { createDefaultGenerators } from '../src/generators';
import { aaravLearner } from '../src/seed/personas';
import { DEFAULT_SIM, diagnosisExperiment, resolutionExperiment, type SimInput } from '../src/sim/learnerSim';

const pack = PACKS[0]!;
const generators = createDefaultGenerators();
const input: SimInput = { pack, generators, cfg: DEFAULT_SIM };
const pct = (x: { p: number; ci: number }) => `${(x.p * 100).toFixed(1)}% (±${(x.ci * 100).toFixed(1)})`;

const t0 = performance.now();
const res = { nova: resolutionExperiment(input, 'nova'), baseline: resolutionExperiment(input, 'baseline') };
const dia = { nova: diagnosisExperiment(input, 'nova'), baseline: diagnosisExperiment(input, 'baseline') };
const ideal: SimInput = { pack, generators, cfg: { ...DEFAULT_SIM, pHold: 1, pSlip: 0, pLearnMatch: 1, pLearnMismatch: 1, budget: 60 } };
const idealRes = { nova: resolutionExperiment(ideal, 'nova'), baseline: resolutionExperiment(ideal, 'baseline') };
const simSeconds = (performance.now() - t0) / 1000;

// ---- engine timing (microseconds per call)
function bench(name: string, fn: () => void, n = 2000) {
  for (let i = 0; i < 200; i++) fn(); // warm up
  const s = performance.now();
  for (let i = 0; i < n; i++) fn();
  return { name, us: ((performance.now() - s) * 1000) / n };
}
const aarav = aaravLearner('a', pack, 1_800_000_000_000);
const ev = aarav.history[aarav.history.length - 1]!;
const gen = pack.questions.find((q) => q.kind === 'generated')!;
let seed = 1;
const timings = [
  bench('applyAttempt (learner with history)', () => applyAttempt(aarav, ev, pack)),
  bench('planToday', () => planToday(aarav, pack, 1_800_000_000_000)),
  bench('selectQuestion', () => selectQuestion({ pack, state: aarav, generators, concept: 'loop-bounds', seed: seed++, focus: ['off-by-one-start'] })),
  bench('generate one question (generator)', () => materializeQuestion(gen, generators, seed++, [])),
  bench('next quick-check question', () => nextDiagnosticQuestion({ pack, generators, events: [], seed: seed++ })),
  bench('createLearner', () => createLearner('x', pack, 0)),
];
const exportBytes = JSON.stringify({ profile: { id: 'a', name: 'Aarav' }, learners: [aarav] }).length;

const cpu = cpus()[0];
const md = `<!-- generated by npm run evidence; do not edit by hand -->
## Simulated learners (${DEFAULT_SIM.learners} per policy, seed ${DEFAULT_SIM.seed})

Pack: **${pack.id}** v${pack.version}. Budget: ${DEFAULT_SIM.budget} questions per learner. Assumptions: a learner with a mistake falls into it ${DEFAULT_SIM.pHold * 100}% of the time when a matching wrong option appears, makes a random wrong answer ${DEFAULT_SIM.pSlip * 100}% of the time otherwise, and an explanation removes the mistake ${DEFAULT_SIM.pLearnMatch * 100}% of the time in the learner's hidden best style and ${DEFAULT_SIM.pLearnMismatch * 100}% in another style.

### Experiment A: how fast are hidden mistakes removed?
| | NOVA | Baseline (memoryless) |
|---|---|---|
| Mean questions until the learner has no mistake left (not resolved = ${DEFAULT_SIM.budget}) | ${res.nova.meanAttemptsToResolve.toFixed(1)} (±${res.nova.ciAttempts.toFixed(1)}) | ${res.baseline.meanAttemptsToResolve.toFixed(1)} (±${res.baseline.ciAttempts.toFixed(1)}) |
| Fully resolved within 20 questions | ${pct(res.nova.resolvedWithin20)} | ${pct(res.baseline.resolvedWithin20)} |
| Fully resolved within ${DEFAULT_SIM.budget} questions | ${pct(res.nova.resolvedWithinBudget)} | ${pct(res.baseline.resolvedWithinBudget)} |
| Mean wrong answers | ${res.nova.meanWrongAnswers.toFixed(1)} | ${res.baseline.meanWrongAnswers.toFixed(1)} |
| Explanations given in the learner's best style | ${(res.nova.bestStyleShare * 100).toFixed(1)}% | ${(res.baseline.bestStyleShare * 100).toFixed(1)}% |

### Experiment C: an ideal learner (always falls into a mistake when offered, always learns from an explanation, never slips; budget 60 questions)
This removes the learner assumptions, so it shows only what the **content and the engine** can do.
| | NOVA | Baseline (memoryless) |
|---|---|---|
| Share of a learner's mistakes that some asked question offered as a wrong answer | ${(idealRes.nova.mistakesOfferedShare * 100).toFixed(1)}% | ${(idealRes.baseline.mistakesOfferedShare * 100).toFixed(1)}% |
| Learners fully resolved within 60 questions | ${pct(idealRes.nova.resolvedWithinBudget)} | ${pct(idealRes.baseline.resolvedWithinBudget)} |
| Learners left with a mistake that a question had already offered but that was not fixed | ${(idealRes.nova.unfixedOfferedShare * 100).toFixed(1)}% | ${(idealRes.baseline.unfixedOfferedShare * 100).toFixed(1)}% |

### Experiment B: does the system find the right mistakes? (teaching switched off, ${DEFAULT_SIM.diagnosisQuestions} questions)
| | NOVA | Baseline |
|---|---|---|
| Precision (flagged mistakes that are real) | ${(dia.nova.precision * 100).toFixed(1)}% | ${(dia.baseline.precision * 100).toFixed(1)}% |
| Recall (real mistakes that were found) | ${(dia.nova.recall * 100).toFixed(1)}% | ${(dia.baseline.recall * 100).toFixed(1)}% |
| F1 | ${(dia.nova.f1 * 100).toFixed(1)}% | ${(dia.baseline.f1 * 100).toFixed(1)}% |

## Engine speed (Node ${process.version}, ${cpu?.model ?? 'unknown CPU'}, ${cpus().length} cores)
| Operation | Mean time |
|---|---|
${timings.map((t) => `| ${t.name} | ${t.us.toFixed(1)} µs |`).join('\n')}

Learner export (Aarav, 15 answers): ${(exportBytes / 1024).toFixed(1)} KB. Simulation run time: ${simSeconds.toFixed(1)} s.
`;
mkdirSync('docs/evidence-data', { recursive: true });
writeFileSync('docs/evidence-data/simulation.md', md);
writeFileSync('docs/evidence-data/simulation.json', JSON.stringify({ config: DEFAULT_SIM, resolution: res, ideal: idealRes, diagnosis: dia, timingsUs: timings, exportBytes }, null, 2) + '\n');
console.log(md);
